import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import DarkModeToggle from "./darkmodebutton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 w-[200%] h-full flex -z-10">
          <div className="w-1/2 h-full bg-[url('../../public/background_images/morning_sky.png')] dark:bg-[url('../../public/background_images/night_sky.png')] bg-no-repeat bg-auto bg-top animate-scroll-left transition-colors duration-700"></div>
          <div className="w-1/2 h-full bg-[url('../../public/background_images/morning_sky.png')] dark:bg-[url('../../public/background_images/night_sky.png')] bg-no-repeat bg-auto bg-top animate-scroll-left transition-colors duration-700"></div>
        </div>
        <div>
          <div className="absolute top-4 right-4 flex flex-col items-end">
            <DarkModeToggle />
          </div>
          <h1 className="text-center text-6xl elrian-font text-violet-700 dark:text-amber-400 transition-colors duration-700">
            Cleanview
          </h1>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
